"""Tests for context module."""

from pathlib import Path

from cinna.context import (
    generate_context_files,
    generate_mcp_json,
    generate_opencode_json,
    generate_gitignore,
    _format_mcp_tools,
)


def test_generate_context_files(workspace_root, sample_config):
    building_ctx = {
        "building_prompt": "You are a helpful agent.\n\n## Guidelines\n- Be nice",
    }

    generate_context_files(building_ctx, sample_config, workspace_root)

    claude_md = (workspace_root / "CLAUDE.md").read_text()
    assert "test-agent" in claude_md
    assert "BUILDING_AGENT.md" in claude_md
    assert "cinna exec" in claude_md

    building_md = (workspace_root / "BUILDING_AGENT.md").read_text()
    assert "auto-generated by cinna" in building_md
    assert "You are a helpful agent." in building_md


def test_generate_mcp_json(workspace_root, sample_config):
    generate_mcp_json(sample_config, workspace_root)

    mcp_json = workspace_root / ".mcp.json"
    assert mcp_json.exists()

    import json
    data = json.loads(mcp_json.read_text())
    assert "mcpServers" in data
    assert "agent-knowledge" in data["mcpServers"]
    server = data["mcpServers"]["agent-knowledge"]
    assert server["command"] == "cinna"
    assert server["args"] == ["mcp-proxy"]


def test_generate_opencode_json(workspace_root, sample_config):
    generate_opencode_json(sample_config, workspace_root)

    opencode_json = workspace_root / "opencode.json"
    assert opencode_json.exists()

    import json
    data = json.loads(opencode_json.read_text())
    assert "mcp" in data
    assert "agent-knowledge" in data["mcp"]
    server = data["mcp"]["agent-knowledge"]
    assert server["type"] == "local"
    assert server["command"] == ["cinna", "mcp-proxy"]
    assert server["enabled"] is True


def test_generate_gitignore(workspace_root):
    generate_gitignore(workspace_root)

    gitignore = workspace_root / ".gitignore"
    assert gitignore.exists()
    content = gitignore.read_text()
    assert ".cinna/" in content
    assert "CLAUDE.md" in content


def test_generate_gitignore_no_overwrite(workspace_root):
    gitignore = workspace_root / ".gitignore"
    gitignore.write_text("# custom\n")

    generate_gitignore(workspace_root)
    assert gitignore.read_text() == "# custom\n"


def test_format_mcp_tools(sample_config):
    result = _format_mcp_tools(sample_config)
    assert "knowledge_query" in result
    assert "api" in result
    assert "faq" in result


def test_format_mcp_tools_no_knowledge():
    from cinna.config import CinnaConfig
    config = CinnaConfig(
        platform_url="https://example.com",
        cli_token="tok",
        agent_id="a1",
        agent_name="test",
        environment_id="e1",
        template="basic",
        container_name="c1",
    )
    result = _format_mcp_tools(config)
    assert "knowledge_query" in result
