"""Generate CLAUDE.md and BUILDING_AGENT.md from building context."""

import importlib.resources
import json
from pathlib import Path
from datetime import datetime, timezone

from cinna.config import CinnaConfig


def _load_template(name: str) -> str:
    """Load a template file from the templates package."""
    return importlib.resources.files("cinna.templates").joinpath(name).read_text()


def generate_context_files(
    building_context: dict,
    config: CinnaConfig,
    workspace_root: Path,
) -> None:
    """Generate CLAUDE.md and BUILDING_AGENT.md from building context response."""
    timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    # --- BUILDING_AGENT.md ---
    building_prompt = building_context.get("building_prompt", "")
    building_md = (
        f"> This file is auto-generated by cinna. Do not edit manually.\n"
        f"> Contains the building mode system prompt pulled from the platform.\n"
        f"> Regenerated on: {timestamp}\n\n"
        f"{building_prompt}"
    )
    (workspace_root / "BUILDING_AGENT.md").write_text(building_md)

    # --- CLAUDE.md ---
    mcp_tools = _format_mcp_tools(config)
    claude_md = _load_template("CLAUDE.md.template").format(
        agent_name=config.agent_name,
        timestamp=timestamp,
        mcp_tools_section=mcp_tools,
    )
    (workspace_root / "CLAUDE.md").write_text(claude_md)


def generate_mcp_json(config: CinnaConfig, workspace_root: Path) -> None:
    """Generate .mcp.json for Claude Code MCP tool discovery."""
    mcp_config = {
        "mcpServers": {
            "agent-knowledge": {
                "command": "cinna",
                "args": ["mcp-proxy"],
                "env": {
                    "CINNA_CONFIG": str(workspace_root / ".cinna" / "config.json"),
                },
            }
        }
    }
    (workspace_root / ".mcp.json").write_text(json.dumps(mcp_config, indent=2) + "\n")


def generate_opencode_json(config: CinnaConfig, workspace_root: Path) -> None:
    """Generate opencode.json for opencode MCP tool discovery."""
    opencode_config = {
        "mcp": {
            "agent-knowledge": {
                "type": "local",
                "command": ["cinna", "mcp-proxy"],
                "environment": {
                    "CINNA_CONFIG": str(workspace_root / ".cinna" / "config.json"),
                },
                "enabled": True,
            }
        }
    }
    (workspace_root / "opencode.json").write_text(
        json.dumps(opencode_config, indent=2) + "\n"
    )


def generate_gitignore(workspace_root: Path) -> None:
    """Generate .gitignore for the local dev workspace."""
    content = """\
.cinna/
.claude/settings.local.json
CLAUDE.md
BUILDING_AGENT.md
.mcp.json
opencode.json
cinna.log
workspace/credentials/
workspace/__pycache__/
workspace/*.pyc
"""
    gitignore = workspace_root / ".gitignore"
    if not gitignore.exists():
        gitignore.write_text(content)


def _format_mcp_tools(config: CinnaConfig) -> str:
    """Format MCP tools list for CLAUDE.md."""
    tools = [
        "- `knowledge_query` — Search the agent's knowledge base for documentation"
    ]
    if config.knowledge_sources:
        topics = ", ".join(t for ks in config.knowledge_sources for t in ks.topics)
        if topics:
            tools.append(f"  Available topics: {topics}")
    return "\n".join(tools)
